// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb7g_ILNCTBUN586a8HOPkre8xCRulZZQ',
    appId: '1:425383502292:web:84d7ae54c7809443df3641',
    messagingSenderId: '425383502292',
    projectId: 'live-streaming-app-bbdee',
    authDomain: 'live-streaming-app-bbdee.firebaseapp.com',
    storageBucket: 'live-streaming-app-bbdee.appspot.com',
    measurementId: 'G-48XGYL14HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6zUODo0JeJ3ZSL36tmqTqRdhQ8C56NXM',
    appId: '1:425383502292:android:31db332b6c7ac52bdf3641',
    messagingSenderId: '425383502292',
    projectId: 'live-streaming-app-bbdee',
    storageBucket: 'live-streaming-app-bbdee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNAKbveKJvb-2CPZ73uy1UO-ihHtlNPio',
    appId: '1:425383502292:ios:05b440c39c078b9cdf3641',
    messagingSenderId: '425383502292',
    projectId: 'live-streaming-app-bbdee',
    storageBucket: 'live-streaming-app-bbdee.appspot.com',
    iosClientId: '425383502292-9vqpdsio1ddf9nbau14v0dohesu503qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStreamingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNAKbveKJvb-2CPZ73uy1UO-ihHtlNPio',
    appId: '1:425383502292:ios:7b00c03f75e20e9adf3641',
    messagingSenderId: '425383502292',
    projectId: 'live-streaming-app-bbdee',
    storageBucket: 'live-streaming-app-bbdee.appspot.com',
    iosClientId: '425383502292-hlrk4c2g992vokmjbf16rcaqrq5gt7uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStreamingApp.RunnerTests',
  );
}
